sonar.projectKey=q1nck7g935vzx2udr86mh0fpbeislo_peerless-lessons-learned
sonar.organization=q1nck7g935vzx2udr86mh0fpbeislo

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=peerless-lessons-learned
